//
//  Commodity.swift
//  Pathfinder
//
//  Created by Adam Michael on 10/15/15.
//  Copyright © 2015 Pathfinder. All rights reserved.
//

import Foundation
import CoreLocation

/**
A commodity that has requested transportation via your application.

This class should never be instantiated directly because it represents the state of the data from the Pathfinder backend. Instead, request commodity transportation via the helper method in the Pathfinder class.
 
A typical use case looks like this:

```swift
let clusterToRouteIn = self.cluster
let start = CLLocationCoordinate2D(latitude: startLat, longitude: startLng)
let end = CLLocationCoordinate2D(latitude: endLat, longitude: endLng)
let metadata = [String:AnyObject]()
metadata["people"] = 2
metadata["sheep"] = 0
let commodity = pathfinder.cluster("/USA/West/Seattle").createCommodity(start, destination: end, metadata: metadata)
commodity.connect()
commodity.request()
```

The primary purpose of creating a commodity is to set its delegate. The delegate will receive updates on the status of the commodity as defined in `CommodityDelegate`.
*/
public class Commodity {

  // MARK: - Enums -

  /// All commodities exist in one of five states: inactive, waiting, picked up, dropped off or cancelled.
  public enum Status : String, CustomStringConvertible {
    case Inactive = "Inactive"
    case Waiting = "Waiting"
    case PickedUp = "PickedUp"
    case DroppedOff = "DroppedOff"
    case Cancelled = "Cancelled"

    public var description: String {
      switch self {
      case .Inactive: return "Inactive"
      case .Waiting: return "Waiting"
      case .PickedUp: return "PickedUp"
      case .DroppedOff: return "DroppedOff"
      case .Cancelled: return "Cancelled"
      }
    }
  }

  // MARK: - Instance Variables

  /// The delegate that will receive notifications when any aspect of the commodity is updated.
  public var delegate: CommodityDelegate?

  /// The unique id of the transport, as generated by Pathfinder.
  public var id: Int?

  /// The starting location of the commodity's journey.
  public var start: CLLocationCoordinate2D?

  /// The destination location of the commodity's journey.
  public var destination: CLLocationCoordinate2D?

  /// The routing parameters, capacities and any other information associated with the commodity.
  public var metadata: [String:AnyObject]?

  /// The route that is assigned to pick up the commodity, if there is one.
  public var route: Route?

  /// The current status of the commodity. All commodities are inactive upon creation.
  public var status: Status = Status.Inactive

  /// The transport that is transporting the commodity. If status is not PickedUp, this will be nil
  public var transport: Transport?

  var cluster: Cluster!

  // MARK: - Methods -

  /// Requests transportation for the current commodity. The status is updated to Status.Waiting.
  public func request() {
    status = .Waiting
    cluster!.connect() { (cluster: Cluster) -> Void in
      self.cluster.conn.create(self) { (resp: CommodityResponse) -> Void in
        self.id = resp.id
      }
    }
  }

  /// Validates and authenticates the Pathfinder connection to the backend data for this instance. If the connection is successful, the corresponding method on the delegate is called. Upon completion, all instance variables will be updated with the data from the Pathfinder service.
  public func connect() {
  }

  /**
  Subscribes to push notifications for all updates to the commodity. The corresponding method on the delegate will be called for the following events:
   
  * Commodity was assigned to a route.
  * Commodity was picked up, dropped off or the request was cancelled.
  */
  public func subscribe() {
    self.cluster.conn.subscribe(self)
  }

  /// Stops the Pathfinder service from sending update notifications.
  public func unsubscribe() {

  }

  /**
  Updates the commodity's status. This can be used to cancel the transportation request or to indicate that the commodity was picked up or dropped off by the transport. Commodities are created with status `Inactive`.
   
  - Parameter status:  The new status of the transport.
  */
  public func update(status: Status) {
    self.cluster.conn.update(self) { (resp: CommodityResponse) -> Void in
      
    }
  }

  init(cluster: Cluster, id: Int) {
    self.cluster = cluster
    self.id = id
  }

  init(id: Int, start: CLLocationCoordinate2D, destination: CLLocationCoordinate2D, metadata: [String:AnyObject]) {
    self.id = id
    self.start = start
    self.destination = destination
    self.metadata = metadata
  }

  init(cluster: Cluster, start: CLLocationCoordinate2D, destination: CLLocationCoordinate2D, metadata: [String:AnyObject]) {
    self.cluster = cluster
    self.start = start
    self.destination = destination
    self.metadata = metadata
  }

  init(cluster: Cluster, id: Int, start: CLLocationCoordinate2D, destination: CLLocationCoordinate2D, metadata: [String:AnyObject]) {
    self.cluster = cluster
    self.id = id
    self.start = start
    self.destination = destination
    self.metadata = metadata
  }

  init(clusterId: String, id: Int, start: CLLocationCoordinate2D, destination: CLLocationCoordinate2D, metadata: [String:AnyObject]) {
    self.id = id
    self.start = start
    self.destination = destination
    self.metadata = metadata
  }

  class func parse(message: NSDictionary) -> Commodity? {
    if let startLat = message["startLatitude"] as? Double {
      if let startLng = message["startLongitude"] as? Double {
        if let endLat = message["endLatitude"] as? Double {
          if let endLng = message["endLongitude"] as? Double {
            if let id = message["id"] as? Int {
              if let metadata = message["metadata"] as? [String:AnyObject] {
                if let statusStr = message["status"] as? String {
                  let status = Commodity.Status(rawValue: statusStr)!
                  let start = CLLocationCoordinate2D(latitude: startLat, longitude: startLng)
                  let end = CLLocationCoordinate2D(latitude: endLat, longitude: endLng)
                  let commodity = Commodity(id: id, start: start, destination: end, metadata: metadata)
                  commodity.status = status
                  return commodity
                }
              }
            }
          }
        }
      }
    }
    return nil
  }
}